AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30

Resources:
  WhereApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.where.api.StreamLambdaHandler::handleRequest
      Runtime: java17
      SnapStart:
        ApplyOn: PublishedVersions
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
      MemorySize: 2048
      Timeout: 60
      Events:
        WhereLambdaAPI:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
